title: Pathfinder
description: Code Pathfinder attempts to be query language for structural search on source code. It's built for identifying vulnerabilities in source code.
theme: just-the-docs

url: https://codepathfinder.dev/
ga_tracking: G-TEBRJVVBGG
color_scheme: dark
favicon_ico: "/assets/images/favicon.ico"
aux_links:
  "Github":
    - "https://github.com/shivasurya/code-pathfinder"
plugins:
  - jekyll-sitemap
