title: Pathfinder
description: Code Pathfinder attempts to be query language for structural search on source code. It's built for identifying vulnerabilities in source code.
theme: just-the-docs

url: https://codepathfinder.dev/
ga_tracking: G-TEBRJVVBGG
